[package]
name = "tut_bellman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bellman = "0.14.0"
bls12_381 = "0.8.0"
ff = "0.13.0"
pairing = "0.23.0"
rand = "0.8.5"
sha = "1.0.3"
sha2 = "0.10.7"
